config/routes.rb
Rails.application.routes.draw do
  #Session
  get "signin" => "session#new", as: "signin"
  post "login" => "session#create", as: "login"
  delete "logout" => "session#destroy", as: "logout"

  # Registration
  get "register" => "register#new", as: "register"
  post "register" => "register#create", as: "new_registration"


  # Projects
  resources :projects

  # Users
  #resources :users
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  NAME_REGEX = /\A[a-zA-Z\-\!\@]+\z/
  EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/

  validates :first_name, format: { with: NAME_REGEX }, length: (2..100)
  validates :last_name, format: { with: NAME_REGEX }, length: (1..100)
  validates :email, format: { with: EMAIL_REGEX }, uniqueness: true
  validate :validate_password

  has_secure_password validations: false

  def self.authenticate(params = {})
    return false unless user = User.find_by_email(params[:email])

    return false unless user.authenticate(params[:password])
    user

  end

private

  def password_valid?
    unless password =~ /[0-9]+/
      errors.add(:password, "must contain at least one number")
    end

    unless password =~ /[a-zA-Z]+/
      errors.add(:password, "must contain at least one letter")
    end

    unless password =~ /[!@#\$&%\^]+/
      errors.add(:password, "must contain one special character (!, @, #, $, &, %, ^)")
    end

    unless (6..100).cover?(password.to_s.length)
      errors.add(:password, "must be at least 6 characters long")
    end
  end

  def validate_password
    password_valid? if new_record? || password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def login_as(user)
    return nil unless user
    session[:user_id] = user.id
    @current_user = user
  end

  def logout_user
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_as(@user)
      flash[:notice] = "You have successfully registered."
      redirect_to projects_path
    else
      render "new"
    end
  end

private

  def  user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    @user = User.authenticate(params[:user])

    if @user
      login_as(@user)
      redirect_to projects_path
    else
      flash[:notice] = "Email or password is incorrect"
      @user = User.new
      render "new"
    end
  end

  def destroy
    logout_user

    redirect_to signin_path
  end
  def new
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper

  def brand_tag(user)
    [].tap do |ary|
      ary << "Basewise"
      ary << ": " if user
      ary << user_name(user)
    end.join("")
  end


  def user_name(user)
    return nil unless user
    "#{user.first_name.capitalize} #{user.last_name.capitalize}"
  end

  def session_links(user)
    if user
      link_to "Log Out", logout_path, method: :delete
    else
      content_tag(:span, class: "session_links") do
        link_to("Sign Up", register_path) +
        "   |   " +
        link_to("Log In", signin_path)
      end
    end
  end
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title || "Basewise") %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="top-nav">
  <%= render "shared/top_nav" %>
</div>

<div class="flash">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
</div>

<div class="main-content">
  <%= yield %>
</div>


</body>
</html>

app/views/projects/index.html.erb
<div class="projects-container">
  <div class="projects-sidebar">
    <%= link_to "#" do %>
      <span>New Project</span>
    <% end %>
  </div>

  <ol class="projects-list">
    <% @projects.each do |project| %>
      <li>
        <span class="title"><%= project.title %></span>
        <span class="description"><%= project.description %></span>
        <span class="updated">Last updated on <%= project.updated_at.strftime("%b %e") %></span>
      </li>
    <% end %>
  </ol>
</div>

app/views/register/create.html.erb
<h1>Register#create</h1>
<p>Find me in app/views/register/create.html.erb</p>

app/views/register/new.html.erb
<% content_for :title, "Register for Basewise" %>


<%= simple_form_for @user, url: new_registration_path do |f| %>
    <%= f.input :email, placeholder: "Email address", error_prefix: "Email" %>
    <%= f.input :first_name, placeholder: "First Name", error_prefix: "First Name" %>
    <%= f.input :last_name, placeholder: "Last Name", error_prefix: "Last Name" %>
    <%= f.input :password, placeholder: "Password", error_prefix: "Password" %>

    <%= f.submit %>

<% end %>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<% content_for :title, "Login to Basewise" %>

<%= simple_form_for @user, url: login_path do |f| %>
    <%= f.input :email, placeholder: "Email address", error_prefix: "Email" %>
    <%= f.input :password, placeholder: "Password", error_prefix: "Password" %>

    <%= f.submit "Login" %>
<% end %>

app/views/shared/_top_nav.html.erb
<nav>
  <ul class="left">
    <li>Basewise:<%= user_name(current_user)%></li>
  </ul>

  <ul class="right">
    <li><%= session_links(current_user) %></li>
  </ul>